name: Custom Commands Github Workflows

on: 
  workflow_dispatch:
    inputs:
      command:
        description: 'What command to execute?'
        required: true
        type: string

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Execute the command specified.
        run: ${{ inputs.command }}
